=== Gonzalo-6/DAW-lenguaje-de-marcas/lenguaje de marcas/xml/22-09/ejercicio 1.dtd
<!ELEMENT casas_rurales (casa+)>
    <!ELEMENT casa (descripcion+, direccion+, estado+, tamanio+, disponible+)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT estado (#PCDATA)>
    <!ELEMENT tamanio (#PCDATA)>
    <!ELEMENT disponible EMPTY>

=== Gonzalo-6/DAW-lenguaje-de-marcas/lenguaje de marcas/xml/22-09/casasrurales.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE casas_rurales SYSTEM "ejercicio 1.dtd"> 

<casas_rurales>
    <casa>  
        <descripcion>
            Casa rural en el centro del pueblo
        </descripcion>
        <direccion>
            Avenida de los rosales
        </direccion>
        <estado>
            disponible
        </estado>
        <tamanio>200m2</tamanio>
        <disponible></disponible>
    </casa>
     <casa>  
        <descripcion>
            Casa rural en el centro del pueblo
        </descripcion>
        <direccion>
            Avenida de los rosales
        </direccion>
        <estado>
            disponible
        </estado>
        <tamanio>200m2</tamanio>
        <disponible></disponible>
    </casa>
</casas_rurales>
